---
- name: Install fail2ban
  become: true
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Configure fail2ban SSH jail
  become: true
  ansible.builtin.template:
    src: fail2ban/jail.d/sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Enable fail2ban service
  become: true
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    state: started
...
