---

- name: Update packages
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install Base packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - vim
    - htop

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Start fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    state: started

...
