---
- name: Include packages tasks
  ansible.builtin.include_tasks: packages.yml
  tags:
    - packages

- name: Include unattended-upgrades tasks
  ansible.builtin.include_tasks: unattended-upgrades.yml
  when: base_unattended_upgrades
  tags:
    - unattended-upgrades

- name: Include SSH hardening tasks
  ansible.builtin.include_tasks: ssh.yml
  when: base_ssh_hardening
  tags:
    - ssh

- name: Include fail2ban tasks
  ansible.builtin.include_tasks: fail2ban.yml
  when: base_fail2ban
  tags:
    - fail2ban

- name: Include UFW tasks
  ansible.builtin.include_tasks: ufw.yml
  when: base_ufw
  tags:
    - ufw

- name: Include timezone tasks
  ansible.builtin.include_tasks: timezone.yml
  tags:
    - timezone
...
