---

- name: Update packages
  become: true
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install Base packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - vim
    - htop

- name: Install fail2ban
  become: true
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Copy jail files to jail.d folder
  become: true
  ansible.builtin.template:
    src: "jail.d/{{ item }}.j2"
    dest: "/etc/fail2ban/jail.d/{{ item }}"
    owner: root
    group: root
    mode: "644"
  loop: "{{ base_jail_files }}"
  notify: Restart fail2ban

- name: Start fail2ban
  become: true
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    state: started

...
