---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Enable NTP synchronization
  become: true
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true
    state: started
...
