---
- name: Install UFW
  become: true
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set default deny incoming
  become: true
  community.general.ufw:
    direction: incoming
    default: deny

- name: Set default allow outgoing
  become: true
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Allow SSH port
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ base_ssh_port | string }}"
    proto: tcp
    comment: SSH

- name: Apply extra rules
  become: true
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    direction: "{{ item.direction | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    port: "{{ item.port | string if item.port is defined else omit }}"
    proto: >-
      {{ item.proto | default('tcp') if item.port is defined
         else item.proto | default(omit) }}
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ base_ufw_extra_rules }}"

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled
...
