---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    virtualbox
platforms:
  - name: instance
    box: ubuntu/jammy64
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../../tests
