---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    libvirt
platforms:
  - name: ansible-role-base-noble
    box: bento/ubuntu-24.04
    memory: 1024
    cpus: 1
  - name: ansible-role-base-jammy
    box: generic/ubuntu2204
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
